repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-symlinks
  - id: check-toml
  - id: check-json
  - id: check-yaml
- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    # exclude: docs/
    # extend-ignore: E203,W501,E266,C901
